name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Run tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: iosBaseApp.xcodeproj
        scheme: iosBaseApp
        destination: platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest
        action: test
    - name: Build App
      run: xcodebuild -project "iosBaseApp.xcodeproj" -scheme "iosBaseApp" -destination "generic/platform=iOS" -allowProvisioningUpdates | xcpretty
    - name: Run CodeCov
      uses: codecov/codecov-action@v1
