name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Build and test
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: iosBaseApp.xcodeproj
        scheme: iosBaseApp
        destination: platform=macOS
        action: test
